services:

  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=laptopshop
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"

    expose:
      - "3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/laptopshop
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-mysql
    # volumes:
    #   db-data:

    # docker compose -p hoidanit-spring-mvc up -d
