eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: product
            uri: http://localhost:8081
            predicates:
              - Path=/api/product/**
          - id: order
            uri: http://localhost:8082
            predicates:
              - Path=/api/order/**
          - id: cart
            uri: http://localhost:8083
            predicates:
              - Path=/api/cart/**
          # - id: product
          #   uri: http://localhost:8081
          #   predicates:
          #     - Path=/api/product/**, /api/supplier/** 
          # - id: order
          #   uri: http://localhost:8082
          #   predicates:
          #     - Path=/api/supplier-order/**, /api/item/**
          # - id: cart
          #   uri: http://localhost:8083
          #   predicates:
          #     - Path=/api/cart/** 

  